<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="19" passed="3" failed="4" skipped="8">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-05T11:40:11 IST" name="Suite" finished-at="2024-07-05T11:40:17 IST" duration-ms="5878">
    <groups>
    </groups>
    <test started-at="2024-07-05T11:40:11 IST" name="Test" finished-at="2024-07-05T11:40:17 IST" duration-ms="5878">
      <class name="com.poppulo.employee_api_tests.CreateEmployeeAPITests">
        <test-method signature="ValidateCustomerApiWithValidData(java.util.HashMap)[pri:1, instance:com.poppulo.employee_api_tests.CreateEmployeeAPITests@2d195ee4]" started-at="2024-07-05T11:40:13 IST" name="ValidateCustomerApiWithValidData" data-provider="data" finished-at="2024-07-05T11:40:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetIndex(XSSFWorkbook.java:1230)
at com.poppulo.util.ExcelReader.getRowCount(ExcelReader.java:52)
at com.poppulo.util.DataUtil.getData(DataUtil.java:23)
at com.poppulo.employee_api_tests.CreateEmployeeAPITests.Data(CreateEmployeeAPITests.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 12 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCustomerApiWithValidData -->
        <test-method signature="ValidateCustomerApiWithInValidData(java.util.HashMap)[pri:2, instance:com.poppulo.employee_api_tests.CreateEmployeeAPITests@2d195ee4]" started-at="2024-07-05T11:40:13 IST" name="ValidateCustomerApiWithInValidData" data-provider="data" finished-at="2024-07-05T11:40:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetIndex(XSSFWorkbook.java:1230)
at com.poppulo.util.ExcelReader.getRowCount(ExcelReader.java:52)
at com.poppulo.util.DataUtil.getData(DataUtil.java:23)
at com.poppulo.employee_api_tests.CreateEmployeeAPITests.Data(CreateEmployeeAPITests.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 12 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCustomerApiWithInValidData -->
        <test-method signature="ValidateMultipleEmployeeCReationWithSameDataAndVerifyUniqueIdForEachEmployee(java.util.HashMap)[pri:3, instance:com.poppulo.employee_api_tests.CreateEmployeeAPITests@2d195ee4]" started-at="2024-07-05T11:40:13 IST" name="ValidateMultipleEmployeeCReationWithSameDataAndVerifyUniqueIdForEachEmployee" data-provider="data" finished-at="2024-07-05T11:40:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetIndex(XSSFWorkbook.java:1230)
at com.poppulo.util.ExcelReader.getRowCount(ExcelReader.java:52)
at com.poppulo.util.DataUtil.getData(DataUtil.java:23)
at com.poppulo.employee_api_tests.CreateEmployeeAPITests.Data(CreateEmployeeAPITests.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 12 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateMultipleEmployeeCReationWithSameDataAndVerifyUniqueIdForEachEmployee -->
        <test-method signature="verifyUniqueEmployeeIds()[pri:4, instance:com.poppulo.employee_api_tests.CreateEmployeeAPITests@2d195ee4]" started-at="2024-07-05T11:40:13 IST" name="verifyUniqueEmployeeIds" finished-at="2024-07-05T11:40:13 IST" depends-on-methods="com.poppulo.employee_api_tests.CreateEmployeeAPITests.ValidateMultipleEmployeeCReationWithSameDataAndVerifyUniqueIdForEachEmployee" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CreateEmployeeAPITests.verifyUniqueEmployeeIds()[pri:4, instance:com.poppulo.employee_api_tests.CreateEmployeeAPITests@2d195ee4] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CreateEmployeeAPITests.verifyUniqueEmployeeIds()[pri:4, instance:com.poppulo.employee_api_tests.CreateEmployeeAPITests@2d195ee4] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUniqueEmployeeIds -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.poppulo.employee_api_tests.CreateEmployeeAPITests@2d195ee4]" started-at="2024-07-05T11:40:17 IST" name="tearDown" finished-at="2024-07-05T11:40:17 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.poppulo.employee_api_tests.CreateEmployeeAPITests -->
      <class name="com.poppulo.employee_api_tests.GetEmployeeAPITest">
        <test-method signature="testGetUserDataSuccess(java.util.HashMap)[pri:1, instance:com.poppulo.employee_api_tests.GetEmployeeAPITest@a50ae65]" started-at="2024-07-05T11:40:13 IST" name="testGetUserDataSuccess" data-provider="getdata" finished-at="2024-07-05T11:40:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetIndex(XSSFWorkbook.java:1230)
at com.poppulo.util.ExcelReader.getRowCount(ExcelReader.java:52)
at com.poppulo.util.DataUtil.getData(DataUtil.java:23)
at com.poppulo.employee_api_tests.GetEmployeeAPITest.Data(GetEmployeeAPITest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 12 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserDataSuccess -->
        <test-method signature="testGetNonExistentUser()[pri:2, instance:com.poppulo.employee_api_tests.GetEmployeeAPITest@a50ae65]" started-at="2024-07-05T11:40:13 IST" name="testGetNonExistentUser" finished-at="2024-07-05T11:40:13 IST" duration-ms="771" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetNonExistentUser -->
      </class> <!-- com.poppulo.employee_api_tests.GetEmployeeAPITest -->
      <class name="com.poppulo.employee_api_tests.UpdateEmployeeAPITest">
        <test-method signature="validateValidEmployeeUpdate(java.util.HashMap)[pri:1, instance:com.poppulo.employee_api_tests.UpdateEmployeeAPITest@56de6d6b]" started-at="2024-07-05T11:40:13 IST" name="validateValidEmployeeUpdate" data-provider="updateData" finished-at="2024-07-05T11:40:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetIndex(XSSFWorkbook.java:1230)
at com.poppulo.util.ExcelReader.getRowCount(ExcelReader.java:52)
at com.poppulo.util.DataUtil.getData(DataUtil.java:23)
at com.poppulo.employee_api_tests.UpdateEmployeeAPITest.Data(UpdateEmployeeAPITest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 12 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateValidEmployeeUpdate -->
        <test-method signature="validateInvalidEmployeeIdUpdate(java.util.HashMap)[pri:2, instance:com.poppulo.employee_api_tests.UpdateEmployeeAPITest@56de6d6b]" started-at="2024-07-05T11:40:13 IST" name="validateInvalidEmployeeIdUpdate" data-provider="updateData" finished-at="2024-07-05T11:40:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetIndex(XSSFWorkbook.java:1230)
at com.poppulo.util.ExcelReader.getRowCount(ExcelReader.java:52)
at com.poppulo.util.DataUtil.getData(DataUtil.java:23)
at com.poppulo.employee_api_tests.UpdateEmployeeAPITest.Data(UpdateEmployeeAPITest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 12 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateInvalidEmployeeIdUpdate -->
        <test-method signature="validateInvalidEmployeeDataUpdate(java.util.HashMap)[pri:3, instance:com.poppulo.employee_api_tests.UpdateEmployeeAPITest@56de6d6b]" started-at="2024-07-05T11:40:13 IST" name="validateInvalidEmployeeDataUpdate" data-provider="updateData" finished-at="2024-07-05T11:40:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetIndex(XSSFWorkbook.java:1230)
at com.poppulo.util.ExcelReader.getRowCount(ExcelReader.java:52)
at com.poppulo.util.DataUtil.getData(DataUtil.java:23)
at com.poppulo.employee_api_tests.UpdateEmployeeAPITest.Data(UpdateEmployeeAPITest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 12 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateInvalidEmployeeDataUpdate -->
      </class> <!-- com.poppulo.employee_api_tests.UpdateEmployeeAPITest -->
      <class name="com.poppulo.employee_api_tests.DeleteEmployeeTest">
        <test-method signature="testVerifyEmployeeDeletion()[pri:1, instance:com.poppulo.employee_api_tests.DeleteEmployeeTest@997d532]" started-at="2024-07-05T11:40:11 IST" name="testVerifyEmployeeDeletion" finished-at="2024-07-05T11:40:14 IST" duration-ms="2481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVerifyEmployeeDeletion -->
        <test-method signature="testDeleteNonExistentEmployee()[pri:2, instance:com.poppulo.employee_api_tests.DeleteEmployeeTest@997d532]" started-at="2024-07-05T11:40:14 IST" name="testDeleteNonExistentEmployee" finished-at="2024-07-05T11:40:14 IST" duration-ms="416" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 404 (Not Found),Able to delete NonExistent employee expected [404] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 404 (Not Found),Able to delete NonExistent employee expected [404] but found [204]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.poppulo.employee_api_tests.DeleteEmployeeTest.testDeleteNonExistentEmployee(DeleteEmployeeTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteNonExistentEmployee -->
        <test-method signature="testDeleteEmployeeWithInvalidIdFormat()[pri:3, instance:com.poppulo.employee_api_tests.DeleteEmployeeTest@997d532]" started-at="2024-07-05T11:40:14 IST" name="testDeleteEmployeeWithInvalidIdFormat" finished-at="2024-07-05T11:40:15 IST" duration-ms="440" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 400 (Bad Request),Able to delete  employee with InvalidIdFormat expected [400] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 400 (Bad Request),Able to delete  employee with InvalidIdFormat expected [400] but found [204]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.poppulo.employee_api_tests.DeleteEmployeeTest.testDeleteEmployeeWithInvalidIdFormat(DeleteEmployeeTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteEmployeeWithInvalidIdFormat -->
        <test-method signature="testDeleteEmployeeWithEmptyId()[pri:4, instance:com.poppulo.employee_api_tests.DeleteEmployeeTest@997d532]" started-at="2024-07-05T11:40:15 IST" name="testDeleteEmployeeWithEmptyId" finished-at="2024-07-05T11:40:15 IST" duration-ms="437" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 400 (Bad Request),Able to delete  employee with empty id expected [400] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 400 (Bad Request),Able to delete  employee with empty id expected [400] but found [204]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.poppulo.employee_api_tests.DeleteEmployeeTest.testDeleteEmployeeWithEmptyId(DeleteEmployeeTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteEmployeeWithEmptyId -->
        <test-method signature="testDeleteEmployeeWithMalformedRequest()[pri:5, instance:com.poppulo.employee_api_tests.DeleteEmployeeTest@997d532]" started-at="2024-07-05T11:40:15 IST" name="testDeleteEmployeeWithMalformedRequest" finished-at="2024-07-05T11:40:15 IST" duration-ms="427" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 400 (Bad Request),Able to delete  employee with malformed delete request expected [400] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 400 (Bad Request),Able to delete  employee with malformed delete request expected [400] but found [204]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.poppulo.employee_api_tests.DeleteEmployeeTest.testDeleteEmployeeWithMalformedRequest(DeleteEmployeeTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteEmployeeWithMalformedRequest -->
        <test-method signature="testSimultaneousDeleteOperations()[pri:6, instance:com.poppulo.employee_api_tests.DeleteEmployeeTest@997d532]" started-at="2024-07-05T11:40:15 IST" name="testSimultaneousDeleteOperations" finished-at="2024-07-05T11:40:17 IST" duration-ms="1633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSimultaneousDeleteOperations -->
      </class> <!-- com.poppulo.employee_api_tests.DeleteEmployeeTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
